easy=??, ???, ??, ????, ??
easy-desc=?????? ???? ??? ?? ?????.\n???? ???? ???, ??? ?? ?????.\n??? ??? ????, ?? ???? ?? ??? ?? ? ? ????.
hard=???, ????, ??, ????, ??
hard-desc=?????? ???? ?? ??? ?? ? ????.\n???? ? ??? ???? ??, ??? ??? ????.\n??? ????? ??? ??? ??? ?? ? ??? ?? ????.