coward=%s the Cowardly
brave=%s the Brave
mighty=%s the Mighty
wise=%s the Wise
ponderous=%s the Ponderous
fierce=%s the Fierce
humble=%s the Humble
intrepid=%s the Intrepid
upperDeck=%s of the Upper Deck
lowerDeck=%s of the Lower Deck