safetyAd1=Papa, we are still waiting for you
safetyAd2={0} DAYS WITHOUT AN ACCIDENT
AlinaIllTheory1-name=Illness of Alina.
AlinaResign-name=Introduction of Alina.
BecameDivLeader-name=I am the infrastructure division leader.
BoyFindingMom-name=A boy with a box.
BoyFindingMom2-name=A boy with a box.
BoyFindingMom3-name=A boy with a box.
BribeDoctor0-name=Illness of Sylvia.
BribeDoctor2-name=Talking with Dr Paik.
BribeDoctor2-title=Talking with Dr Paik.
BribeDoctor2-desc=Talk to Dr Paik in the Welfare Station East.
BribeDoctor3-name=Talking with Dr Paik.
BribeDoctor3-title=Investigate the water storage.
BribeDoctor3-desc=Talk to Dr Paik about the water storage at the Welfare Station East.
BribeDoctor4-name=Talking with Dr Paik.
BribeDoctor5-name=Illness of Sylvia.
DelayRepair1-name=Agros comes by and asks to delay repairing the ammonia production system.
ElectionApproaching-name=The election is approaching.
ElectionApproaching-title=The election is approaching.
ElectionApproaching-desc=The election is approaching.
ExpiredWorkplaceInformation-name=Expired Workplace Information: %s
ExpiredWorkplaceInformation-title=You must be kept updated on situations of %s.
ExpiredWorkplaceInformation-desc=Examine it yourself or request your employees to do so.
GenuineRequest-name=A reasonable request: %s
GenuineRequest-title=Request from %s.
GenuineRequest-desc=You were requested to work on %s.
HatefulDirectReport-name=A direct report hates you: %s
HatefulDirectReport-title=Your authority is being questioned in %s.
HatefulDirectReport-desc=Improve relations with your direct reports.
ImprovePartyIntegrity-name=Improve Party Integrity: %s
ImprovePartyIntegrity-title=Members of %s are not getting along.
ImprovePartyIntegrity-desc=You must improve the integrity of %s.
KrailinDrunk1-name=Rambling of Krailin
KrailinHobby1-name=Rambling of Krailin
KrailinHobby2-name=Rambling of Krailin
ObserverIntro1-name=Introduction of the Observer.
ObserverIntro2-name=Introduction of the Observer.
ObserverIntro3-name=Introduction of the Observer.
ObserverIntroAfterMeeting1-name=Mysterious orders from the Observer.
ObserverIntroAfterMeeting1-title=Mysterious orders from the Observer
ObserverIntroAfterMeeting1-desc=The Observer has told you to pay a visit to the Observatory.
ObserverIntroAfterMeeting2-name=Mysterious orders from the Observer.
PaySalary-name=Pay Salary: %s
PaySalary-title=Salary of %s is not paid yet.
PaySalary-desc=Pay the salary in the daily meeting.
PrologueAlinaAccident-name=Introduction of Alina.
PrologueAlinaAccident2-name=Interrogation
PrologueAlinaSpeech-name=Introduction of Alina.
PrologueAlinaSpeech-title=Alina's speech
PrologueAlinaSpeech-desc=Alina is giving a speech to the Infrastructure Division.
ProposeBudget-name=Propose Budget: %s
ProposeBudget-title=Quarterly budget of %s is not proposed yet.
ProposeBudget-desc=Attend the budget proposal meeting.
ResolveBudget-name=Resolve Budget: %s
ResolveBudget-title=Quarterly budget of %s is not resolved yet.
ResolveBudget-desc=Attend the budget resolution meeting.
SalvorElection-name=Salvor speaks in the election.
SecureOuterBarrierEast-name=Introduction of Alina.
SecureOuterBarrierEast-title=Secure the Outer Barrier East Barrier
SecureOuterBarrierEast-desc=Keep the barrier durability above 50.
YuhoaIntro-name=Introduction of Yuhoa

