fontKeys=fixedsys,GrotleyRegular,Martius,MartiusEnglish
fixedsys.file=fonts/LondrinaSolid-Regular.ttf
fixedsys.size=20
GrotleyRegular.file=fonts/LondrinaSolid-Regular.ttf
GrotleyRegular.size=75
Martius.file=fonts/Martius-LV9L4.ttf
Martius.size=75
MartiusEnglish.file=fonts/Martius-LV9L4.ttf
MartiusEnglish.size=75
charset=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890~`!@#$%^&*(){}[]-_=+;:'",<.>/?\|
