Talk=Oi, give me a sec.
Talk-Rare-coworker-positive-1=Been a while. You still holding up out there?
Talk-Rare-coworker-positive-1-duration=1.5
Talk-Rare-coworker-positive-2=Always. Let's not waste time then.
Talk-Rare-coworker-positive-2-speaker=other
Talk-Rare-coworker-positive-2-duration=1.1
Talk-Rare-Rui=You're new, but you've got grit. I can work with that.
